FROM php:7.0.8-apache
RUN docker-php-ext-install mysqli

#docker run --name mysql-app -e MYSQL_ROOT_PASSWORD=1234 -d mysql:latest
#docker build -t php-app:02 .
#docker run --name final-app -v /home/aprendephp/docker_training/notes/04_php_outsourcing/localfiles/:/var/www/html/ --link mysql-app -d php-app:02