version: '2'
services:
  php:
    build: .
    container_name: final-app
    image: php:latest
    volumes:
      - /home/aprendephp/docker_training/notes/07_compose_network/localfiles/:/var/www/html/
    depends_on:
      - mysql
    networks:
      my_net:
        ipv4_address: 172.28.5.10
  mysql:
    container_name: mysql-app
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ../data_dir:/var/lib/mysql
    networks:
      my_net:
        ipv4_address: 172.28.5.11
networks:
  my_net:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
