version: '2'
services:
  php:
    build: .
    container_name: final-app
    image: php:latest
    volumes:
      - ../06_php_code:/var/www/html/
    depends_on:
      - mysql
  mysql:
    container_name: mysql-app
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ../06_mysql_data:/var/lib/mysql

