version: '2'
services:
  php:
    build: .
    container_name: final-app
    image: php:latest
    volumes:
      - /home/aprendephp/docker_training/notes/06_compose/localfiles/:/var/www/html/
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    container_name: mysql-app
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - /home/aprendephp/docker_training/notes/06_compose/data_dir:/var/lib/mysql

